# This file was generated by GoReleaser. DO NOT EDIT.
cask "gophermind" do
  version "0.1.0"

  on_macos do
    sha256 "7dd6ca81ab9eae2a0b34ec1c7d0a54389d7f1d11e7de64841037530a12a7de30"
    url "https://github.com/jbrahy/gophermind.com/releases/download/v#{version}/gophermind_#{version}_darwin_all.tar.gz"
  end

  on_linux do
    on_intel do
      sha256 "e2757589173b663128f1bed999d9bfc153b15a2312d9d87fd6c98a271359411a"
      url "https://github.com/jbrahy/gophermind.com/releases/download/v#{version}/gophermind_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "06dda5b8ffb6d4ac1d818ad48d1a9f2ad67cfc10bed2dd3ba74f2e99f60e1098"
      url "https://github.com/jbrahy/gophermind.com/releases/download/v#{version}/gophermind_#{version}_linux_arm64.tar.gz"
    end
  end

  name "gophermind"
  desc "A minimal agentic coding harness for OpenAI-compatible LLMs"
  homepage "https://github.com/jbrahy/gophermind.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gophermind"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gophermind"]
    end
  end

  # No zap stanza required

end
