# This file was generated by GoReleaser. DO NOT EDIT.
cask "gophermind" do
  version "0.7.0"

  on_macos do
    sha256 "f979615a6b9188935e73733f457e0aaa1543cb29d614b7e69d09161b7ae6b0b8"
    url "https://github.com/jbrahy/gophermind.com/releases/download/v#{version}/gophermind_#{version}_darwin_all.tar.gz"
  end

  on_linux do
    on_intel do
      sha256 "6e719ed93d8fa88295aa4bde9e10ec711d1ad556b7a9e82b3aea7cd613ead084"
      url "https://github.com/jbrahy/gophermind.com/releases/download/v#{version}/gophermind_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "3e462040a4b046156333407c17e3bcc27543ba1f67925b27cb6d5798093e6910"
      url "https://github.com/jbrahy/gophermind.com/releases/download/v#{version}/gophermind_#{version}_linux_arm64.tar.gz"
    end
  end

  name "gophermind"
  desc "A minimal agentic coding harness for OpenAI-compatible LLMs"
  homepage "https://github.com/jbrahy/gophermind.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gophermind"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gophermind"]
    end
  end

  # No zap stanza required

end
