# GopherMind Desktop.
#
# Generated by scripts/build-desktop.sh from
# packaging/gophermind-desktop.rb.tmpl, which fills in the version and the
# checksum together so the two cannot drift apart. Edit the template, not this
# file.
#
# A separate cask from `gophermind`, which installs the CLI. Either can be
# installed without the other: the app embeds its own server rather than
# shelling out to the CLI binary.
cask "gophermind-desktop" do
  version "0.7.0"
  sha256 "b218c9ba0d3dccfe1fe63e6b4ac55ff5bec181395c7b8359d86adbf62192273f"

  url "https://github.com/jbrahy/gophermind.com/releases/download/v#{version}/GopherMind-Desktop_#{version}_darwin_universal.zip"
  name "GopherMind Desktop"
  desc "Desktop application for the GopherMind agentic coding harness"
  homepage "https://github.com/jbrahy/gophermind.com"

  depends_on macos: ">= :big_sur"

  app "GopherMind Desktop.app"

  # No quarantine-stripping hook here, unlike the gophermind CLI cask. The
  # bundle carries a stapled notarization ticket, so Gatekeeper clears it
  # offline without one. Stripping the attribute anyway would hide a genuinely
  # broken signature behind a workaround.

  zap trash: [
    "~/Library/Application Support/gophermind",
    "~/Library/Preferences/com.jbrahy.gophermind.desktop.plist",
    "~/Library/Saved Application State/com.jbrahy.gophermind.desktop.savedState",
  ]
end
