# This file was generated by GoReleaser. DO NOT EDIT.
cask "gophermind" do
  version "0.2.0"

  on_macos do
    sha256 "dcdc60e1bba4583a2afccf3a72413856ceb76f1a49b9890e2057b1f1cace59c9"
    url "https://github.com/jbrahy/gophermind.com/releases/download/v#{version}/gophermind_#{version}_darwin_all.tar.gz"
  end

  on_linux do
    on_intel do
      sha256 "78e2755a62bd77bbd57adc74283ab89d2d672b4d6b1a8443cdeb9ed48e4f0a37"
      url "https://github.com/jbrahy/gophermind.com/releases/download/v#{version}/gophermind_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "9537f3410cecd1842281a09be9d3d7c5b5413a97cb2aadebde4a57ea9b6fb6de"
      url "https://github.com/jbrahy/gophermind.com/releases/download/v#{version}/gophermind_#{version}_linux_arm64.tar.gz"
    end
  end

  name "gophermind"
  desc "A minimal agentic coding harness for OpenAI-compatible LLMs"
  homepage "https://github.com/jbrahy/gophermind.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gophermind"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gophermind"]
    end
  end

  # No zap stanza required

end
